### ISSUE TITLE
Unable to initialize Deezer API

### ISSUE THREAD

**Issue by mR12KL** [s3condAtall/Deezloader#6]
Seems Deezer has updated their API and it no longer works! Keep getting "Unable to initialize Deezer API"

**Comment by simpleme11** [comment]
Yep it doesn't work anymore.
I'm getting the same error.
someone on reddit said this method works but it doesn't.
It launches deezloader nothing happens when you download songs.

Deezloader-2.0.3-win\node_modules\node-deezer-api\index.js

Replace line 34:

var regex = new RegExp("checkForm = '(.*)'");

With:

var regex = new RegExp("checkForm = \"(.*)\"");

Will get it (mostly) working

**Comment by QrchackOfficial** [comment]
@simpleme11 It won't "get it (mostly) working", this "fix" just makes the code invalid by terminating the parameter.

**Comment by s3condAtall** [comment]
# @mR12KL @simpleme11 @QrchackOfficial Fixed.. Try and report..
